# Generated by Django 5.1.1 on 2024-09-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
